apiVersion: v1
kind: Secret
metadata:
  name: neon-db-secret
  namespace: frontend
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL25lb25kYl9vd25lcjpucGdfTG9RNVJCSmppZjJrQGVwLXN0aWxsLW1lYWRvdy1hNGh6cGxpci1wb29sZXIudXMtZWFzdC0xLmF3cy5uZW9uLnRlY2gvbmVvbmRiP3NzbG1vZGU9cmVxdWlyZQ==
